spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    payment-url: http://localhost:8222/api/v1/payments
    product-url: http://localhost:8222/api/v1/products


  kafka:
   producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.support.serialization.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.spark.ecommerce.kafka.OrderConfirmation